version: '2'

services:
  domainrequests:
    container_name: imagehasher
    image: imghash

    volumes:
      - ~/Documents/docker/imghash/data:/code/data
      - ~/Documents/docker/imghash/source:/code/source